name: 'world_cup_analytics'
version: '1.0.0'
config-version: 2

profile: 'world_cup_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  world_cup_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
