{% macro translate_team_name(column_name) %}
CASE {{ column_name }}
    WHEN 'Argentina' THEN 'Argentina'
    WHEN 'Australia' THEN 'Austrália'
    WHEN 'Austria' THEN 'Áustria'
    WHEN 'Belgium' THEN 'Bélgica'
    WHEN 'Bosnia-Herzegovina' THEN 'Bósnia e Herzegovina'
    WHEN 'Brazil' THEN 'Brasil'
    WHEN 'Canada' THEN 'Canadá'
    WHEN 'Cape Verde Islands' THEN 'Cabo Verde'
    WHEN 'Colombia' THEN 'Colômbia'
    WHEN 'Congo DR' THEN 'Congo DR'
    WHEN 'Croatia' THEN 'Croácia'
    WHEN 'Czechia' THEN 'República Tcheca'
    WHEN 'Ecuador' THEN 'Equador'
    WHEN 'Egypt' THEN 'Egito'
    WHEN 'England' THEN 'Inglaterra'
    WHEN 'France' THEN 'França'
    WHEN 'Germany' THEN 'Alemanha'
    WHEN 'Ghana' THEN 'Gana'
    WHEN 'Haiti' THEN 'Haiti'
    WHEN 'Iran' THEN 'Irã'
    WHEN 'Iraq' THEN 'Iraque'
    WHEN 'Ivory Coast' THEN 'Costa do Marfim'
    WHEN 'Japan' THEN 'Japão'
    WHEN 'Jordan' THEN 'Jordânia'
    WHEN 'Mexico' THEN 'México'
    WHEN 'Morocco' THEN 'Marrocos'
    WHEN 'Netherlands' THEN 'Holanda'
    WHEN 'New Zealand' THEN 'Nova Zelândia'
    WHEN 'Norway' THEN 'Noruega'
    WHEN 'Panama' THEN 'Panamá'
    WHEN 'Paraguay' THEN 'Paraguai'
    WHEN 'Portugal' THEN 'Portugal'
    WHEN 'Qatar' THEN 'Catar'
    WHEN 'Saudi Arabia' THEN 'Arábia Saudita'
    WHEN 'Scotland' THEN 'Escócia'
    WHEN 'Senegal' THEN 'Senegal'
    WHEN 'South Africa' THEN 'África do Sul'
    WHEN 'South Korea' THEN 'Coreia do Sul'
    WHEN 'Spain' THEN 'Espanha'
    WHEN 'Sweden' THEN 'Suécia'
    WHEN 'Switzerland' THEN 'Suíça'
    WHEN 'Tunisia' THEN 'Tunísia'
    WHEN 'Turkey' THEN 'Turquia'
    WHEN 'United States' THEN 'Estados Unidos'
    WHEN 'Uruguay' THEN 'Uruguai'
    WHEN 'Uzbekistan' THEN 'Uzbequistão'
    WHEN 'Algeria' THEN 'Argélia'
    WHEN 'Curaçao' THEN 'Curaçao'
    ELSE {{ column_name }}
END
{% endmacro %}